---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.13
  commands:
  - go test -race ./...

- name: coverage
  image: golang:1.13
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - go test -race -coverprofile=coverage.out -covermode=atomic
  - curl -s https://codecov.io/bash | bash

---
kind: signature
hmac: 9e30feaddbddfeff5ec204959459fe14257786edb6a14f6e2e26403405698787

...
